export const enum NamespaceEnum {
  SESSION = 'session',
  CONNECT = 'connect',
  DISCONNECT = 'disconnect',
  LOGIN = 'login',
  LOGOUT = 'logout',
  CREATE_ROOM = 'create-room',
  JOIN_ROOM = 'join-room',
  WAIT_ROOM = 'wait-room',
  EDIT_ROOM = 'edit-room',
  LEAVE_ROOM = 'leave-room',
  PLAYER_IN = 'player-in',
  PLAYER_OUT = 'player-out',
  PLAYER_DISCONNECTED = 'player-disconnected',
  PLAYER_RECONNECTED = 'player-reconnected',
  ROOM_EDITED = 'room-edited',
  START_GAME = 'start-game',
  SEND_CHAT = 'send-chat',
  RECEIVE_CHAT = 'receive-chat',
  VOICE_READY = 'voice-ready',
  VOICE_CANDIDATE = 'voice-candidate',
  VOICE_OFFER = 'voice-offer',
  VOICE_ANSWER = 'voice-answer',
  DEBUG_INITIALIZE = 'initialize',
}
