version: '3.8' # Minimum version of Docker required

services:
  mongo1:
    container_name: mongo1
    image: mongo:5.0
    env_file:
      - ../.env
    entrypoint: ['/bin/bash', '/etc/entrypoint.sh']
    # restart: always
    ports:
      - 27017:27017
    volumes:
      - ./replica.key:/pki/replica.key
      - ./mongod.conf:/etc/mongod.conf
      - ./entrypoint.sh:/etc/entrypoint.sh
      - ./init-replica.js:/etc/init-replica.js
      - ./init-db.js:/etc/init-db.js
      - mongo1_data:/data/db
      - mongo1_config:/data/configdb

  mongo2:
    image: mongo:5.0
    container_name: mongo2
    env_file:
      - ../.env
    entrypoint: ['/bin/bash', '/etc/entrypoint.sh']
    # restart: always
    ports:
      - 27018:27017
    volumes:
      - ./replica.key:/pki/replica.key
      - ./mongod.conf:/etc/mongod.conf
      - ./entrypoint.sh:/etc/entrypoint.sh
      - ./init-replica.js:/etc/init-replica.js
      - ./init-db.js:/etc/init-db.js
      - mongo2_data:/data/db
      - mongo2_config:/data/configdb

  mongo3:
    image: mongo:5.0
    container_name: mongo3
    env_file:
      - ../.env
    entrypoint: ['/bin/bash', '/etc/entrypoint.sh']
    # restart: always
    ports:
      - 27019:27017
    volumes:
      - ./replica.key:/pki/replica.key
      - ./mongod.conf:/etc/mongod.conf
      - ./entrypoint.sh:/etc/entrypoint.sh
      - ./init-replica.js:/etc/init-replica.js
      - ./init-db.js:/etc/init-db.js
      - mongo3_data:/data/db
      - mongo3_config:/data/configdb

volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data:
  mongo1_config:
  mongo2_config:
  mongo3_config:
